name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck
      
      - name: Run shellcheck
        run: |
          shellcheck scripts/*.sh
          shellcheck src/**/*.sh
          shellcheck online_install.sh

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, debian-latest]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc curl jq
      
      - name: Run tests
        run: bash tests/test_monitor.sh

  install-test:
    name: Installation Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Test installation script
        run: sudo bash scripts/install.sh --test 